_target_: src.lightning_model.LungLitModel
network_name: "BackboneClassifier2D"
lr: 1e-4
num_classes: 2
feature_dim: 1280
backbone_name: "resnet18"
freeze_half: false
checkpoint_path: null
model_cfg: null
ckpt: null
attention_type: "soft"
max_slices: 1000
enable_segmentation: False
segmentation_feature_dim: 256
segmentation_loss_weight: 0.1
pos_weight: 150
patch_size: 128
img_size: [512,512]
num_heads: 8
embedding_dim: 512
supervise_attention: false
attention_loss_weight: 0.5

loss:
    name: "BCEWithLogitsLoss"

optimizer:
    name: "AdamW"
    eps: 1e-8
    weight_decay: 1e-2

scheduler:
    name: "CosineAnnealingLR"
    T_max: 10
    eta_min: 1e-6