network_name: DinoDetector
num_classes: 0 # Not used for detector
feature_dim: 384 # For dinov2_vits14
optimizer:
  name: AdamW
  weight_decay: 0.01
scheduler:
  name: CosineAnnealingLR
  T_max: 10
  eta_min: 1e-6
lr: 1e-4
ckpt: null
