defaults:
  - model: dino_detector
  - data: detect
  - trainer: default
  - _self_

seed: 42
project_name: "lung_ct_3d2d_synthesis"
stage: detect

exp:
    name: "dino_detector_experiment"
    base_dir: "./outputs/${exp.name}"

test_split: test  

monitor:
  metric: val/map
  loss: val/loss
  mode: max

hydra:
  run:
    dir: ./outputs/${exp.name}
  job_logging:
    disable_existing_loggers: true
