defaults:
  - model: default
  - data: default
  - trainer: default
  - _self_

seed: 42
project_name: "lung_ct_3d2d_synthesis"
stage: classify

exp:
    name: "2d_resnet18_512_512"
    base_dir: "./outputs/${exp.name}"

test_split: test  

monitor:
  metric: val/mean_auroc
  loss: val/loss
  mode: max

hydra:
  run:
    dir: ./outputs/${exp.name}  # Hydra scriverà log/output qui
  job_logging:
    disable_existing_loggers: true